-- SCRIPT DE CREACIÓN DE BASE DE DATOS TiendaInsumosOficina (MySQL)
-- Adaptado desde FARMACIA para una tienda de insumos de papelería, oficina y colegio

CREATE DATABASE IF NOT EXISTS TiendaInsumosOficina CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE TiendaInsumosOficina;

-- =============================
-- TABLAS DE DIMENSIONES (DB_*)
-- =============================

CREATE TABLE DB_ARTICULO (
    ID_ARTICULO INT AUTO_INCREMENT PRIMARY KEY,
    CODIGO_ARTICULO VARCHAR(50) NOT NULL UNIQUE,
    NOMBRE_ARTICULO VARCHAR(200) NOT NULL,
    DESCRIPCION TEXT,
    CATEGORIA VARCHAR(100),
    SUBCATEGORIA VARCHAR(100),
    MARCA VARCHAR(100),
    PROVEEDOR VARCHAR(100),
    PRECIO_UNITARIO DECIMAL(10,2),
    MONEDA VARCHAR(10) DEFAULT 'USD',
    ESTADO VARCHAR(20) DEFAULT 'ACTIVO',
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50),
    MODIFIED_BY VARCHAR(50)
);

CREATE TABLE DB_CLIENTE (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    CODIGO_CLIENTE VARCHAR(50) NOT NULL UNIQUE,
    NOMBRE_CLIENTE VARCHAR(200) NOT NULL,
    APELLIDO_CLIENTE VARCHAR(200),
    TIPO_DOCUMENTO VARCHAR(20),
    NUMERO_DOCUMENTO VARCHAR(50),
    EMAIL VARCHAR(150),
    TELEFONO VARCHAR(20),
    DIRECCION VARCHAR(300),
    CIUDAD VARCHAR(100),
    ESTADO_PROVINCIA VARCHAR(100),
    PAIS VARCHAR(100),
    CODIGO_POSTAL VARCHAR(20),
    FECHA_NACIMIENTO DATE,
    GENERO VARCHAR(10),
    ESTADO VARCHAR(20) DEFAULT 'ACTIVO',
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50),
    MODIFIED_BY VARCHAR(50)
);

CREATE TABLE DB_PROVEEDOR (
    ID_PROVEEDOR INT AUTO_INCREMENT PRIMARY KEY,
    CODIGO_PROVEEDOR VARCHAR(50) NOT NULL UNIQUE,
    NOMBRE_PROVEEDOR VARCHAR(200) NOT NULL,
    RAZON_SOCIAL VARCHAR(300),
    RUC_NIT VARCHAR(50),
    EMAIL VARCHAR(150),
    TELEFONO VARCHAR(20),
    DIRECCION VARCHAR(300),
    CIUDAD VARCHAR(100),
    ESTADO_PROVINCIA VARCHAR(100),
    PAIS VARCHAR(100),
    CODIGO_POSTAL VARCHAR(20),
    CONTACTO_PRINCIPAL VARCHAR(200),
    ESTADO VARCHAR(20) DEFAULT 'ACTIVO',
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50),
    MODIFIED_BY VARCHAR(50)
);

CREATE TABLE DB_EMPLEADO (
    ID_EMPLEADO INT AUTO_INCREMENT PRIMARY KEY,
    CODIGO_EMPLEADO VARCHAR(50) NOT NULL UNIQUE,
    NOMBRE_EMPLEADO VARCHAR(200) NOT NULL,
    APELLIDO_EMPLEADO VARCHAR(200),
    CARGO VARCHAR(100),
    DEPARTAMENTO VARCHAR(100),
    EMAIL VARCHAR(150),
    TELEFONO VARCHAR(20),
    FECHA_CONTRATACION DATE,
    SALARIO DECIMAL(10,2),
    JEFE_DIRECTO INT,
    ESTADO VARCHAR(20) DEFAULT 'ACTIVO',
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    FOREIGN KEY (JEFE_DIRECTO) REFERENCES DB_EMPLEADO(ID_EMPLEADO)
);

CREATE TABLE DB_SUCURSAL (
    ID_SUCURSAL INT AUTO_INCREMENT PRIMARY KEY,
    CODIGO_SUCURSAL VARCHAR(50) NOT NULL UNIQUE,
    NOMBRE_SUCURSAL VARCHAR(200) NOT NULL,
    DIRECCION VARCHAR(300),
    CIUDAD VARCHAR(100),
    ESTADO_PROVINCIA VARCHAR(100),
    PAIS VARCHAR(100),
    CODIGO_POSTAL VARCHAR(20),
    TELEFONO VARCHAR(20),
    EMAIL VARCHAR(150),
    GERENTE INT,
    ESTADO VARCHAR(20) DEFAULT 'ACTIVO',
    FECHA_APERTURA DATE,
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50),
    MODIFIED_BY VARCHAR(50),
    FOREIGN KEY (GERENTE) REFERENCES DB_EMPLEADO(ID_EMPLEADO)
);

CREATE TABLE DB_TIEMPO (
    ID_TIEMPO INT AUTO_INCREMENT PRIMARY KEY,
    FECHA DATE NOT NULL UNIQUE,
    ANIO INT NOT NULL,
    MES INT NOT NULL,
    DIA INT NOT NULL,
    TRIMESTRE INT NOT NULL,
    SEMESTRE INT NOT NULL,
    DIA_SEMANA INT NOT NULL,
    NOMBRE_MES VARCHAR(20),
    NOMBRE_DIA_SEMANA VARCHAR(20),
    ES_FIN_SEMANA BOOLEAN DEFAULT 0,
    ES_FERIADO BOOLEAN DEFAULT 0,
    NOMBRE_FERIADO VARCHAR(100)
);

-- =============================
-- TABLAS DE HECHOS (HB_*)
-- =============================

CREATE TABLE HB_VENTAS (
    ID_VENTA INT AUTO_INCREMENT PRIMARY KEY,
    ID_ARTICULO INT NOT NULL,
    ID_CLIENTE INT NOT NULL,
    ID_EMPLEADO INT NOT NULL,
    ID_SUCURSAL INT NOT NULL,
    ID_TIEMPO INT NOT NULL,
    CODIGO_VENTA VARCHAR(50) NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIO_UNITARIO DECIMAL(10,2) NOT NULL,
    DESCUENTO DECIMAL(10,2) DEFAULT 0,
    IMPUESTO DECIMAL(10,2) DEFAULT 0,
    TOTAL_VENTA DECIMAL(12,2) NOT NULL,
    FECHA_VENTA DATETIME NOT NULL,
    HORA_VENTA TIME,
    METODO_PAGO VARCHAR(50),
    NUMERO_FACTURA VARCHAR(100),
    ESTADO_VENTA VARCHAR(20) DEFAULT 'COMPLETADA',
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50),
    FOREIGN KEY (ID_ARTICULO) REFERENCES DB_ARTICULO(ID_ARTICULO),
    FOREIGN KEY (ID_CLIENTE) REFERENCES DB_CLIENTE(ID_CLIENTE),
    FOREIGN KEY (ID_EMPLEADO) REFERENCES DB_EMPLEADO(ID_EMPLEADO),
    FOREIGN KEY (ID_SUCURSAL) REFERENCES DB_SUCURSAL(ID_SUCURSAL),
    FOREIGN KEY (ID_TIEMPO) REFERENCES DB_TIEMPO(ID_TIEMPO)
);

CREATE TABLE HB_COMPRAS (
    ID_COMPRA INT AUTO_INCREMENT PRIMARY KEY,
    ID_ARTICULO INT NOT NULL,
    ID_PROVEEDOR INT NOT NULL,
    ID_EMPLEADO INT NOT NULL,
    ID_SUCURSAL INT NOT NULL,
    ID_TIEMPO INT NOT NULL,
    CODIGO_COMPRA VARCHAR(50) NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIO_UNITARIO DECIMAL(10,2) NOT NULL,
    DESCUENTO DECIMAL(10,2) DEFAULT 0,
    IMPUESTO DECIMAL(10,2) DEFAULT 0,
    TOTAL_COMPRA DECIMAL(12,2) NOT NULL,
    FECHA_COMPRA DATETIME NOT NULL,
    NUMERO_ORDEN VARCHAR(100),
    NUMERO_FACTURA VARCHAR(100),
    ESTADO_COMPRA VARCHAR(20) DEFAULT 'COMPLETADA',
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50),
    FOREIGN KEY (ID_ARTICULO) REFERENCES DB_ARTICULO(ID_ARTICULO),
    FOREIGN KEY (ID_PROVEEDOR) REFERENCES DB_PROVEEDOR(ID_PROVEEDOR),
    FOREIGN KEY (ID_EMPLEADO) REFERENCES DB_EMPLEADO(ID_EMPLEADO),
    FOREIGN KEY (ID_SUCURSAL) REFERENCES DB_SUCURSAL(ID_SUCURSAL),
    FOREIGN KEY (ID_TIEMPO) REFERENCES DB_TIEMPO(ID_TIEMPO)
);

CREATE TABLE HB_INVENTARIO (
    ID_INVENTARIO INT AUTO_INCREMENT PRIMARY KEY,
    ID_ARTICULO INT NOT NULL,
    ID_SUCURSAL INT NOT NULL,
    ID_TIEMPO INT NOT NULL,
    STOCK_INICIAL INT DEFAULT 0,
    ENTRADAS INT DEFAULT 0,
    SALIDAS INT DEFAULT 0,
    STOCK_FINAL INT NOT NULL,
    STOCK_MINIMO INT DEFAULT 0,
    STOCK_MAXIMO INT DEFAULT 0,
    FECHA_INVENTARIO DATE NOT NULL,
    COSTO_PROMEDIO DECIMAL(10,2),
    VALOR_INVENTARIO DECIMAL(12,2),
    ESTADO VARCHAR(20) DEFAULT 'ACTIVO',
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50),
    FOREIGN KEY (ID_ARTICULO) REFERENCES DB_ARTICULO(ID_ARTICULO),
    FOREIGN KEY (ID_SUCURSAL) REFERENCES DB_SUCURSAL(ID_SUCURSAL),
    FOREIGN KEY (ID_TIEMPO) REFERENCES DB_TIEMPO(ID_TIEMPO)
);

-- =============================
-- TABLAS DEL SISTEMA (sys_*)
-- =============================

CREATE TABLE sys_configuracion (
    ID_CONFIG INT AUTO_INCREMENT PRIMARY KEY,
    PARAMETRO VARCHAR(100) NOT NULL UNIQUE,
    VALOR VARCHAR(500) NOT NULL,
    DESCRIPCION TEXT,
    TIPO_DATO VARCHAR(20) DEFAULT 'VARCHAR',
    ESTADO VARCHAR(20) DEFAULT 'ACTIVO',
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50),
    MODIFIED_BY VARCHAR(50)
);

CREATE TABLE sys_etl_log (
    ID_LOG INT AUTO_INCREMENT PRIMARY KEY,
    PROCESO VARCHAR(100) NOT NULL,
    FECHA_INICIO DATETIME NOT NULL,
    FECHA_FIN DATETIME,
    ESTADO VARCHAR(20) NOT NULL,
    MENSAJE TEXT,
    REGISTROS_PROCESADOS INT DEFAULT 0,
    REGISTROS_EXITOSOS INT DEFAULT 0,
    REGISTROS_ERRORES INT DEFAULT 0,
    DURACION_SEGUNDOS INT,
    CREATED_BY VARCHAR(50)
);

CREATE TABLE sys_errores_etl (
    ID_ERROR INT AUTO_INCREMENT PRIMARY KEY,
    ID_LOG INT,
    TIPO_ERROR VARCHAR(50) NOT NULL,
    TABLA_ORIGEN VARCHAR(100),
    CAMPO_ERROR VARCHAR(100),
    VALOR_ERROR VARCHAR(500),
    DESCRIPCION_ERROR TEXT,
    FECHA_ERROR DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_LOG) REFERENCES sys_etl_log(ID_LOG)
);

CREATE TABLE sys_usuarios (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_USUARIO VARCHAR(100) NOT NULL UNIQUE,
    EMAIL VARCHAR(150) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    NOMBRE_COMPLETO VARCHAR(200),
    ROL VARCHAR(50) DEFAULT 'USER',
    ESTADO VARCHAR(20) DEFAULT 'ACTIVO',
    ULTIMO_LOGIN DATETIME,
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50),
    MODIFIED_BY VARCHAR(50)
);

-- =============================
-- ÍNDICES ADICIONALES
-- =============================
CREATE INDEX IX_DB_ARTICULO_CODIGO ON DB_ARTICULO(CODIGO_ARTICULO);
CREATE INDEX IX_DB_CLIENTE_CODIGO ON DB_CLIENTE(CODIGO_CLIENTE);
CREATE INDEX IX_DB_PROVEEDOR_CODIGO ON DB_PROVEEDOR(CODIGO_PROVEEDOR);
CREATE INDEX IX_DB_EMPLEADO_CODIGO ON DB_EMPLEADO(CODIGO_EMPLEADO);
CREATE INDEX IX_DB_SUCURSAL_CODIGO ON DB_SUCURSAL(CODIGO_SUCURSAL);
CREATE INDEX IX_DB_TIEMPO_FECHA ON DB_TIEMPO(FECHA);
CREATE INDEX IX_DB_TIEMPO_ANIO_MES ON DB_TIEMPO(ANIO, MES);
CREATE INDEX IX_HB_VENTAS_FECHA ON HB_VENTAS(FECHA_VENTA);
CREATE INDEX IX_HB_VENTAS_ARTICULO ON HB_VENTAS(ID_ARTICULO);
CREATE INDEX IX_HB_VENTAS_CLIENTE ON HB_VENTAS(ID_CLIENTE);
CREATE INDEX IX_HB_VENTAS_SUCURSAL ON HB_VENTAS(ID_SUCURSAL);
CREATE INDEX IX_HB_COMPRAS_FECHA ON HB_COMPRAS(FECHA_COMPRA);
CREATE INDEX IX_HB_COMPRAS_ARTICULO ON HB_COMPRAS(ID_ARTICULO);
CREATE INDEX IX_HB_COMPRAS_PROVEEDOR ON HB_COMPRAS(ID_PROVEEDOR);
CREATE INDEX IX_HB_COMPRAS_SUCURSAL ON HB_COMPRAS(ID_SUCURSAL);
CREATE INDEX IX_HB_INVENTARIO_FECHA ON HB_INVENTARIO(FECHA_INVENTARIO);
CREATE INDEX IX_HB_INVENTARIO_ARTICULO ON HB_INVENTARIO(ID_ARTICULO);
CREATE INDEX IX_HB_INVENTARIO_SUCURSAL ON HB_INVENTARIO(ID_SUCURSAL);
CREATE INDEX IX_SYS_ETL_LOG_FECHA ON sys_etl_log(FECHA_INICIO);
CREATE INDEX IX_SYS_ETL_LOG_PROCESO ON sys_etl_log(PROCESO);
CREATE INDEX IX_SYS_ERRORES_ETL_TIPO ON sys_errores_etl(TIPO_ERROR);
CREATE INDEX IX_SYS_ERRORES_ETL_FECHA ON sys_errores_etl(FECHA_ERROR);

-- =============================
-- DATOS INICIALES
-- =============================
INSERT INTO sys_configuracion (PARAMETRO, VALOR, DESCRIPCION, TIPO_DATO, CREATED_BY) VALUES
('VERSION_SISTEMA', '1.0.0', 'Versión actual del sistema', 'VARCHAR', 'SYSTEM'),
('MAX_ERRORES_ETL', '1000', 'Máximo número de errores permitidos en proceso ETL', 'INT', 'SYSTEM'),
('TIMEOUT_ETL_SEGUNDOS', '3600', 'Timeout en segundos para procesos ETL', 'INT', 'SYSTEM'),
('EMAIL_NOTIFICACIONES', 'admin@tiendaoficina.com', 'Email para notificaciones del sistema', 'VARCHAR', 'SYSTEM'),
('MONEDA_DEFAULT', 'USD', 'Moneda por defecto del sistema', 'VARCHAR', 'SYSTEM'),
('IDIOMA_DEFAULT', 'ES', 'Idioma por defecto del sistema', 'VARCHAR', 'SYSTEM'),
('BACKUP_RETENTION_DAYS', '30', 'Días de retención para backups', 'INT', 'SYSTEM'),
('LOG_RETENTION_DAYS', '90', 'Días de retención para logs', 'INT', 'SYSTEM');

INSERT INTO sys_usuarios (NOMBRE_USUARIO, EMAIL, PASSWORD_HASH, NOMBRE_COMPLETO, ROL, CREATED_BY) VALUES
('admin', 'admin@tiendaoficina.com', 'CHANGE_ME_ON_FIRST_LOGIN', 'Administrador del Sistema', 'ADMIN', 'SYSTEM'),
('etl_user', 'etl@tiendaoficina.com', 'CHANGE_ME_ON_FIRST_LOGIN', 'Usuario ETL', 'ETL_USER', 'SYSTEM');

-- =============================
-- NOTA SOBRE PROCEDIMIENTOS Y ROLES
-- =============================
-- Los procedimientos almacenados y la gestión de roles/permisos deben adaptarse manualmente en MySQL.
-- La población de la tabla de tiempo debe hacerse con un script externo o procedimiento adaptado a MySQL.
